using System;
using System.Collections.Generic;
using System.IO;
using System.Text;
using OmniHid.Core.Abstractions;
using OmniHid.Core.Transport;

namespace OmniHid.Core.Diagnostics
{
    /// <summary>
    /// Generates structured hardware specifications, markdown telemetry dumps,
    /// and AI-ready reverse engineering prompts for unsupported peripheral devices.
    /// </summary>
    public static class SpecificationExporter
    {
        // ═══════════════════════════════════════════════════════════════════════
        // Markdown Specification Export
        // ═══════════════════════════════════════════════════════════════════════

        /// <summary>
        /// Generates a comprehensive markdown telemetry specification file for the given peripheral.
        /// </summary>
        /// <param name="transport">Active HID transport layer for querying feature reports.</param>
        /// <param name="devName">Device model display name.</param>
        /// <param name="vid">USB Vendor ID.</param>
        /// <param name="pid">USB Product ID.</param>
        /// <param name="interfaces">List of HID interfaces belonging to the device.</param>
        /// <param name="outputFilePath">Target filesystem destination path for the markdown document.</param>
        public static void ExportMarkdownSpecification(
            IHidTransport transport,
            string devName,
            ushort vid,
            ushort pid,
            List<HidDeviceInfo> interfaces,
            string outputFilePath)
        {
            if (string.IsNullOrEmpty(outputFilePath)) throw new ArgumentNullException("outputFilePath");

            var fp = IcFingerprinter.Identify(vid, pid, interfaces, devName);

            using (var sw = new StreamWriter(outputFilePath, false, Encoding.UTF8))
            {
                sw.WriteLine("# Hardware Telemetry Specification: {0} (0x{1:X4}:0x{2:X4})", devName, vid, pid);
                sw.WriteLine();
                sw.WriteLine("> Generated by OmniHID Diagnostic Engine on {0:yyyy-MM-dd HH:mm:ss}", DateTime.Now);
                sw.WriteLine();

                // Section 1: Overview
                sw.WriteLine("## 1. Device Overview");
                sw.WriteLine();
                sw.WriteLine("| Property | Value |");
                sw.WriteLine("|---|---|");
                sw.WriteLine("| **Model Name** | {0} |", devName);
                sw.WriteLine("| **USB Vendor ID** | `0x{0:X4}` |", vid);
                sw.WriteLine("| **USB Product ID** | `0x{0:X4}` |", pid);
                sw.WriteLine("| **Identified IC Family** | {0} |", fp.ChipsetFamily);
                sw.WriteLine("| **Identification Confidence** | {0} |", fp.Confidence);
                sw.WriteLine("| **Non-Battery Hardware?** | {0} |", fp.IsNonBatteryDevice ? "Yes (Skip battery probing)" : "No (Battery device)");
                sw.WriteLine("| **Total HID Endpoints** | {0} |", interfaces != null ? interfaces.Count : 0);
                sw.WriteLine();

                if (!string.IsNullOrEmpty(fp.Description))
                {
                    sw.WriteLine("### Architecture Notes");
                    sw.WriteLine("{0}", fp.Description);
                    sw.WriteLine();
                }

                if (!string.IsNullOrEmpty(fp.RecommendedApproach))
                {
                    sw.WriteLine("### Recommended Polling / Driver Approach");
                    sw.WriteLine("{0}", fp.RecommendedApproach);
                    sw.WriteLine();
                }

                // Section 2: Endpoints
                sw.WriteLine("## 2. HID Interface Collections (Endpoints)");
                sw.WriteLine();
                sw.WriteLine("| # | Usage Page | Usage | InLen | OutLen | FeatLen | Path |");
                sw.WriteLine("|---|---|---|---|---|---|---|");

                if (interfaces != null)
                {
                    for (int i = 0; i < interfaces.Count; i++)
                    {
                        var ep = interfaces[i];
                        sw.WriteLine("| {0} | `0x{1:X4}` | `0x{2:X4}` | {3}B | {4}B | {5}B | `{6}` |",
                            i + 1, ep.UsagePage, ep.Usage,
                            ep.InputReportByteLength, ep.OutputReportByteLength, ep.FeatureReportByteLength, ep.DevicePath);
                    }
                }
                sw.WriteLine();

                // Section 3: Feature Report Probes
                sw.WriteLine("## 3. Responding Feature Reports (Baseline Probes)");
                sw.WriteLine();
                byte[] candidateFeatureIds = new byte[] {
                    0x00, 0x01, 0x02, 0x03, 0x04, 0x05, 0x06, 0x07, 0x08, 0x09, 0x0A, 0x0B, 0x0C,
                    0x10, 0x11, 0x12, 0x20, 0x80, 0x81, 0x82, 0x83, 0x84, 0x8F
                };

                int respondedFeatCount = 0;
                if (transport != null && interfaces != null)
                {
                    for (int i = 0; i < interfaces.Count; i++)
                    {
                        var ep = interfaces[i];
                        int featLen = Math.Max(64, ep.FeatureReportByteLength > 0 ? (int)ep.FeatureReportByteLength : 64);

                        foreach (byte fid in candidateFeatureIds)
                        {
                            byte[] buf = new byte[featLen];
                            if (transport.GetFeatureReport(ep.DevicePath, fid, buf) && HasNonZeroData(buf))
                            {
                                respondedFeatCount++;
                                sw.WriteLine("### EP #{0} (`0x{1:X4}:0x{2:X4}`) - Feature Report `0x{3:X2}`", i + 1, ep.UsagePage, ep.Usage, fid);
                                sw.WriteLine("```");
                                sw.WriteLine(FormatHex(buf, 32));
                                sw.WriteLine("```");
                                sw.WriteLine();
                            }
                        }
                    }
                }

                if (respondedFeatCount == 0)
                {
                    sw.WriteLine("*No non-zero Feature Reports responded to standard polled queries.*");
                    sw.WriteLine();
                }

                // Section 4: AI Prompt
                sw.WriteLine("## 4. Prompt for AI Assistant / Protocol Generator");
                sw.WriteLine();
                sw.WriteLine("Copy and paste the following prompt into your LLM assistant (e.g. Gemini, Claude, ChatGPT) to generate the complete driver code:");
                sw.WriteLine();
                sw.WriteLine("````markdown");
                sw.WriteLine("I am developing an open-source C# library called OmniHID (Windows USB HID Peripheral Telemetry).");
                sw.WriteLine("Here is the hardware specification dump for an unsupported device:");
                sw.WriteLine("- Device: {0}", devName);
                sw.WriteLine("- Vendor ID: 0x{0:X4}", vid);
                sw.WriteLine("- Product ID: 0x{0:X4}", pid);
                sw.WriteLine("- Architecture: {0}", fp.ChipsetFamily);
                sw.WriteLine("- Recommended Approach: {0}", fp.RecommendedApproach);
                sw.WriteLine();
                sw.WriteLine("Based on the endpoint topology and Feature Report dumps in this specification:");
                sw.WriteLine("1. Implement a complete C# class implementing `IProtocolHandler` for OmniHID.");
                sw.WriteLine("2. Generate a matching JSON profile file for `devices/`.");
                sw.WriteLine("3. Handle battery percentage calculation, charging status flags, and offline detection.");
                sw.WriteLine("````");
                sw.WriteLine();
            }
        }

        // ═══════════════════════════════════════════════════════════════════════
        // Internal Helpers
        // ═══════════════════════════════════════════════════════════════════════

        private static bool HasNonZeroData(byte[] buf)
        {
            if (buf == null || buf.Length == 0) return false;
            for (int i = 0; i < buf.Length; i++)
            {
                if (buf[i] != 0) return true;
            }
            return false;
        }

        private static string FormatHex(byte[] data, int maxBytes)
        {
            if (data == null || data.Length == 0) return "";
            int len = Math.Min(data.Length, maxBytes);
            var sb = new StringBuilder();
            for (int i = 0; i < len; i++)
            {
                sb.Append(data[i].ToString("X2"));
                if (i < len - 1) sb.Append(" ");
            }
            if (data.Length > maxBytes) sb.Append(" ...");
            return sb.ToString();
        }
    }
}
